import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Inter fontunu import ediyoruz
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] }); // Fontu yüklüyoruz

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Fontu body'e uyguluyoruz */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

 